### ISSUE TITLE
Move?

### ISSUE THREAD

**Issue by quincylvania** [publicdomainmap/presentations#1]
@jessbeutler I added Jim's slides over to https://github.com/publicdomainmap/publicdomainmap.org/tree/gh-pages/slides/ so that they'd be live over at https://publicdomainmap.org/slides/sotmus2022/. Should we just use the website repo instead of this one?

**Comment by jessbeutler** [comment]
Yeah, that's a good idea.

**Comment by quincylvania** [comment]
Presentations are now at https://github.com/publicdomainmap/publicdomainmap.org/tree/main/slides
